# Generated by Django 4.2.7 on 2023-12-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Localidade",
                "verbose_name_plural": "Localidades",
                "db_table": "website_city",
                "ordering": ["-id"],
            },
        ),
    ]
