# Generated by Django 5.0 on 2023-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="city",
            table=None,
        ),
    ]
