# Generated by Django 5.0 on 2023-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("event_date", models.DateField(verbose_name="Data do Acontecimento")),
            ],
            options={
                "verbose_name": "Acontecimento",
                "verbose_name_plural": "Acontecimentos",
                "ordering": ["-id"],
            },
        ),
    ]
