exclude: 'docs|vendor|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      -   id: flake8
          args: [--max-line-length=120]
