exclude: 'docs|vendor|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
#        -   id: end-of-file-fixer
        -   id: check-yaml

    -   repo: https://github.com/asottile/pyupgrade
        rev: v1.25.0
        hooks:
        -   id: pyupgrade
            args: [--py36-plus]

    -   repo: https://github.com/PyCQA/flake8
        rev: 4.0.1
        hooks:
          -   id: flake8
              args: [--max-line-length=131]

    -   repo: https://github.com/timothycrosley/isort
        rev: 5.7.0
        hooks:
          - id: isort

    -   repo: https://github.com/pycqa/flake8

        rev: 3.8.4
        hooks:
            - id: flake8
              args: ['--config=setup.cfg']
              additional_dependencies: [flake8-isort]
