# Generated by Django 4.2.7 on 2023-11-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="user",
        ),
    ]
