# Generated by Django 4.2.7 on 2023-11-30 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cardbank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Banco do cartão",
                "verbose_name_plural": "Bancos do cartão",
                "db_table": "website_cardbank",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "more_infos",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Infos Complementares",
                    ),
                ),
                ("datagasto", models.DateField(verbose_name="Data do Gasto")),
                (
                    "total",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "description_on_invoice",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Descrição na fatura",
                    ),
                ),
                (
                    "opcoes_cartao",
                    models.CharField(
                        choices=[
                            ("C", "Crédito"),
                            ("D", "Débito"),
                            ("T", "Transferência"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="Tipo de pagamento",
                    ),
                ),
                (
                    "card_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cardbanks",
                        to="gasto.cardbank",
                        verbose_name="Banco do cartão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "db_table": "website_gasto",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Segmento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Ativa"), (False, "Inativa")], default=True
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tipo de comércio"),
                ),
            ],
            options={
                "verbose_name": "Segmento do Comercio",
                "verbose_name_plural": "Segmentos do Comercio",
                "db_table": "website_segmento",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Parcelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcelas",
                    models.IntegerField(default=1, verbose_name="Total de parcelas"),
                ),
                (
                    "numero_parcela",
                    models.IntegerField(default=1, verbose_name="Número da parcela"),
                ),
                (
                    "valor_parcela",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Valor da Parcela",
                    ),
                ),
                (
                    "data_parcela",
                    models.DateField(
                        blank=True, null=True, verbose_name="Installment Date"
                    ),
                ),
                (
                    "gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas_gasto",
                        to="gasto.gasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela do gasto",
                "verbose_name_plural": "Parcelas dos gasto",
                "db_table": "website_parcelas",
            },
        ),
        migrations.AddField(
            model_name="gasto",
            name="segmento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segmento",
                to="gasto.segmento",
            ),
        ),
    ]
