# Generated by Django 4.2.7 on 2023-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gasto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cardbank",
            table=None,
        ),
        migrations.AlterModelTable(
            name="gasto",
            table=None,
        ),
        migrations.AlterModelTable(
            name="parcelas",
            table=None,
        ),
        migrations.AlterModelTable(
            name="segmento",
            table=None,
        ),
    ]
