# Generated by Django 5.0 on 2023-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gasto", "0002_alter_cardbank_table_alter_gasto_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gasto",
            options={
                "ordering": ["-datagasto"],
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
            },
        ),
        migrations.AlterModelOptions(
            name="segmento",
            options={
                "ordering": ["-name"],
                "verbose_name": "Segmento",
                "verbose_name_plural": "Segmentos",
            },
        ),
        migrations.AlterField(
            model_name="parcelas",
            name="data_parcela",
            field=models.DateField(blank=True, null=True, verbose_name="Data Parcela"),
        ),
    ]
